import React from 'react'
import { useState, useEffect } from 'react'
import { createPortal } from 'react-dom';

import GridLoader from 'react-spinners/GridLoader'
import NOTE from '../../../constants/summary'


const Modal = ({ show, submitComment, onClose }) => {
  if (!show) return null;

  return createPortal(
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
      <div className="bg-white rounded-lg p-6 w-96">
        <textarea
          className="w-full h-32 p-4 rounded-lg focus:outline-none"
          placeholder="Enter your text here"
        ></textarea>
        <button
          className="mt-4 bg-[#491DB6] text-white px-4 py-2 rounded-lg w-full"
          onClick={() => onClose()}
        >
          Submit
        </button>
        <button onClick={() => onClose()} className='mt-2 text-[#491DB6] bg-gray-200 px-4 py-2 rounded-lg w-full'>Close</button>
      </div>
    </div>,
    document.body
  );
};

export default function CommentsCard({ comments }) {
  const [commentsArr, setComments] = useState([])
  const [isLoading, setIsLoading] = useState(false)
  const [showModal, setShowModal] = useState(false);

  const toggleModal = () => setShowModal(!showModal);

  useEffect(() => {
    const sortedComments = comments.slice().reverse()
    setComments(sortedComments)
  }, [])

  async function summariseComments() {
    setIsLoading(true);
    await new Promise((resolve) => setTimeout(resolve, 3000));
    let commentsArrCopy = commentsArr.slice()
    commentsArrCopy.unshift({notes: NOTE, dateAndTime: "Generated by AI"})
    setComments(commentsArrCopy)
    setIsLoading(false);
  }


  return (
    <div className='bg-white rounded-2xl w-[350px] flex flex-col p-4'>
      <div className='flex flex-row justify-evenly items-center'>
        <p className='text-xl'>Teachers' Comments</p>
      </div>
      <div className='bg-gray-300 h-[40vh] overflow-y-scroll rounded-lg mt-2 flex flex-col pb-2'>
        <GridLoader 
        color={'#491DB6'}
        loading={isLoading}
        className='self-center my-6'
        />
        {commentsArr.reverse().map((comment, index) => 
          <div key={index} className='flex flex-col bg-white text-justify mx-2 mt-2 p-2 rounded-lg'>
            {comment.notes}
            <p className='self-end text-gray-300 text-xs'>{comment.dateAndTime}</p>
          </div>
        )}
      </div>
      <button onClick={() => summariseComments()} className='bg-[#491DB6] text-white rounded-lg px-2 py-1 mt-4'>Summarise with AI</button>
      <button onClick={() => toggleModal()} className='text-[#491DB6] bg-gray-200 rounded-lg px-2 py-1 mt-2'>New Comment</button>
      <Modal show={showModal} onClose={toggleModal} />
  </div>
  )
}
