const STUDENTS = [
  {
    student_id: 1,
    name: "Wei Jie Tan",
    email: "weijie.tan@example.com",
    dob: "2024-05-15",
    class_name: "3A",
  },
  {
    student_id: 2,
    name: "Mei Ling Lim",
    email: "meiling.lim@example.com",
    dob: "2024-08-22",
    class_name: "3A",
  },
  {
    student_id: 3,
    name: "Jia Hui Ng",
    email: "jiahui.ng@example.com",
    dob: "2024-02-18",
    class_name: "3A",
  },
  {
    student_id: 4,
    name: "Yong Sheng Lee",
    email: "yongsheng.lee@example.com",
    dob: "2024-11-30",
    class_name: "3A",
  },
  {
    student_id: 5,
    name: "Li Xian Wong",
    email: "lixian.wong@example.com",
    dob: "2024-03-25",
    class_name: "3A",
  },
  {
    student_id: 6,
    name: "Zhi Hao Chua",
    email: "zhihao.chua@example.com",
    dob: "2024-06-17",
    class_name: "3A",
  },
  {
    student_id: 7,
    name: "Hui Min Goh",
    email: "huimin.goh@example.com",
    dob: "2024-10-09",
    class_name: "3A",
  },
  {
    student_id: 8,
    name: "Jun Wei Tan",
    email: "junwei.tan@example.com",
    dob: "2024-12-05",
    class_name: "3A",
  },
  {
    student_id: 9,
    name: "Ying Yue Ong",
    email: "yingyue.ong@example.com",
    dob: "2024-01-22",
    class_name: "3A",
  },
  {
    student_id: 10,
    name: "Kai Wen Teo",
    email: "kaiwen.teo@example.com",
    dob: "2024-04-14",
    class_name: "3A",
  },
  {
    student_id: 11,
    name: "Lian Heng Tan",
    email: "lianheng.tan@example.com",
    dob: "2024-06-12",
    class_name: "3C",
  },
  {
    student_id: 12,
    name: "Pei Ling Lim",
    email: "peiling.lim@example.com",
    dob: "2024-09-08",
    class_name: "3C",
  },
  {
    student_id: 13,
    name: "Yi Xuan Ng",
    email: "yixuan.ng@example.com",
    dob: "2024-01-20",
    class_name: "3C",
  },
  {
    student_id: 14,
    name: "Shi Min Lee",
    email: "shimin.lee@example.com",
    dob: "2024-04-30",
    class_name: "3C",
  },
  {
    student_id: 15,
    name: "Chun Wei Wong",
    email: "chunwei.wong@example.com",
    dob: "2024-07-14",
    class_name: "3C",
  },
  {
    student_id: 16,
    name: "Mei Xing Chua",
    email: "meixing.chua@example.com",
    dob: "2024-03-11",
    class_name: "3C",
  },
  {
    student_id: 17,
    name: "Jia Ming Goh",
    email: "jiaming.goh@example.com",
    dob: "2024-10-25",
    class_name: "3C",
  },
  {
    student_id: 18,
    name: "Hui Xin Ong",
    email: "huixin.ong@example.com",
    dob: "2024-12-05",
    class_name: "3C",
  },
  {
    student_id: 19,
    name: "Wei Ling Tan",
    email: "weiling.tan@example.com",
    dob: "2024-02-13",
    class_name: "3C",
  },
  {
    student_id: 20,
    name: "Liang Wei Teo",
    email: "liangwei.teo@example.com",
    dob: "2024-11-02",
    class_name: "3C",
  },
  {
    student_id: 21,
    name: "Wei Liang Tan",
    email: "weiliang.tan@example.com",
    dob: "2024-07-15",
    class_name: "3A",
  },
  {
    student_id: 22,
    name: "Mei Xuan Lim",
    email: "meixuan.lim@example.com",
    dob: "2024-09-12",
    class_name: "3A",
  },
  {
    student_id: 23,
    name: "Jun Hong Ng",
    email: "junhong.ng@example.com",
    dob: "2024-11-21",
    class_name: "3A",
  },
  {
    student_id: 24,
    name: "Yi Ling Lee",
    email: "yiling.lee@example.com",
    dob: "2024-01-19",
    class_name: "3A",
  },
  {
    student_id: 25,
    name: "Jing Wen Wong",
    email: "jingwen.wong@example.com",
    dob: "2024-03-28",
    class_name: "3A",
  },
  {
    student_id: 26,
    name: "Zi Hao Chua",
    email: "zihao.chua@example.com",
    dob: "2024-06-03",
    class_name: "3A",
  },
  {
    student_id: 27,
    name: "Hui Ying Goh",
    email: "huiying.goh@example.com",
    dob: "2024-08-18",
    class_name: "3A",
  },
  {
    student_id: 28,
    name: "Wei Ming Tan",
    email: "weiming.tan@example.com",
    dob: "2024-10-07",
    class_name: "3A",
  },
  {
    student_id: 29,
    name: "Pei Wen Lim",
    email: "peiwen.lim@example.com",
    dob: "2024-12-14",
    class_name: "3A",
  },
  {
    student_id: 30,
    name: "Zhi Hui Ng",
    email: "zhihui.ng@example.com",
    dob: "2024-02-25",
    class_name: "3A",
  },
  {
    student_id: 31,
    name: "Ying Xuan Lee",
    email: "yingxuan.lee@example.com",
    dob: "2024-04-02",
    class_name: "3A",
  },
  {
    student_id: 32,
    name: "Jia Min Wong",
    email: "jiamin.wong@example.com",
    dob: "2024-07-20",
    class_name: "3A",
  },
  {
    student_id: 33,
    name: "Hui Min Chua",
    email: "huimin.chua@example.com",
    dob: "2024-09-15",
    class_name: "3A",
  },
  {
    student_id: 34,
    name: "Jing Xuan Goh",
    email: "jingxuan.goh@example.com",
    dob: "2024-11-05",
    class_name: "3A",
  },
  {
    student_id: 35,
    name: "Yi Jing Tan",
    email: "yijing.tan@example.com",
    dob: "2024-01-29",
    class_name: "3A",
  },
  {
    student_id: 36,
    name: "Liang Hong Lim",
    email: "lianghong.lim@example.com",
    dob: "2024-03-10",
    class_name: "3A",
  },
  {
    student_id: 37,
    name: "Wei Yan Ng",
    email: "weiyan.ng@example.com",
    dob: "2024-06-22",
    class_name: "3A",
  },
  {
    student_id: 38,
    name: "Ying Jie Lee",
    email: "yingjie.lee@example.com",
    dob: "2024-08-03",
    class_name: "3A",
  },
  {
    student_id: 39,
    name: "Mei Yi Wong",
    email: "meiyi.wong@example.com",
    dob: "2024-10-12",
    class_name: "3A",
  },
  {
    student_id: 40,
    name: "Zi Xuan Chua",
    email: "zixuan.chua@example.com",
    dob: "2024-12-28",
    class_name: "3A",
  },
];

export default STUDENTS;
